### ISSUE TITLE
Bug in JavaScript scrollwheel zoom handling which causes slide rule zooming and movement to lock up.

### ISSUE THREAD

**Issue by colinhowell** [HERCsMusicSystems/Sliderule-Simulator-or-Emulator#15]
There is a serious bug in the JavaScript code for handling zooming via the scrollwheel, causing the slide rule to get "locked" in the upper left corner at the default zoom, so that further attempts to either zoom or drag become impossible.

Fortunately, the bug is easily fixed. The culprit is here, in the onwheel handler function:

https://github.com/HERCsMusicSystems/Sliderule-Simulator-or-Emulator/blob/754afd657e9bf34eb0c21f05edac3cb21494fc34/react/sliderule_application.js#L133-L144

The problem is that no default value has been provided for `delta` on line 135, and the code assumes that `event.deltaY` for the wheel event must be non-zero. This is not necessarily true. For example, my MacBook Pro uses its trackpad as the "scrollwheel", and it is very easy to generate a horizontal wheel event with a zero value for `event.deltaY`.

As soon as this happens, the rest of the function will break. Since `delta` starts as undefined and `event.deltaY` is zero, neither of the two following `event.deltaY` conditionals on lines 136-137 fire, and `delta` remains undefined. Then, when `offset` is initialized on line 140, the undefined value of `delta` causes both of `offset`'s components to be set to NaN (Not a Number), because using an undefined value in any math operation will generate a NaN result. Likewise, `sliderules.position` gets its x and y components set to NaN, and `sliderules.scale` is set to undefined, which causes trouble in the sliderule drawing code. The NaN or undefined values stick, because they will "poison" any further updates to their values.

My fix is simple: change line 135 to set `delta` to `sliderules.scale` as a default value. If `event.deltaY` is non-zero, `delta` will immediately be overwritten and things will proceed normally. But if `event.deltaY` is zero, this default value for `delta` will make the rest of the code behave as a no-op, leaving the values of `sliderules.position` and `sliderules.scale` unchanged by the event. In other words, horizontal scroll events will be effectively ignored, which will do what you want.

**Comment by colinhowell** [comment]
@HERCsMusicSystems Apologies for the ping, but just wondering if you've noticed this?

**Comment by HERCsMusicSystems** [comment]
Issue resolved in git commit: 02b8b79.
